# Profile information
name: srmonda
title: Srmonda's blog
url: "srmonda.github.io"

# Social
facebook: "kinhi.tumadam"

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
include: [_pages]
